@url = http://127.0.0.1:3021
	
### GET ALL EMPLOYEES
{{url}}/employees
	
### ADD AN EMPLOYEE
POST {{url}}/employees
content-type: application/json
	
{
	"firstName": "James",
	"lastName": "Tester",
	"age": 55,
	"hireDate": "2020-01-01",
	"employeeNumber": "D-8811"
}